source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '7.0'
inhibit_all_warnings!
pod 'SDWebImage'
pod 'KVOController'
pod 'SSKeychain'
pod 'pop'
pod 'JSONModel'
pod 'AFNetworking'
pod 'RETableViewManager'
pod 'TTTAttributedLabel'
pod 'HHRouter'
pod 'JDStatusBarNotification'
pod 'NJKWebViewProgress'
pod 'GPUImage'
pod 'FMDB'
pod 'ActionSheetPicker-3.0'
pod 'EGOCache'
pod 'Masonry'
pod 'AsyncDisplayKit'